// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjO8eeJWIad5gjVLk9Z-s2lNqQg6lwFBI',
    appId: '1:638773305398:web:a402c582ff70547daaf897',
    messagingSenderId: '638773305398',
    projectId: 'mysudoku-386bc',
    authDomain: 'mysudoku-386bc.firebaseapp.com',
    storageBucket: 'mysudoku-386bc.firebasestorage.app',
    measurementId: 'G-9FFF0XKFH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgf46yyivoqgJWmSm61ARTBJ0bU1ikpXg',
    appId: '1:638773305398:android:f5f6eabcdf5d7090aaf897',
    messagingSenderId: '638773305398',
    projectId: 'mysudoku-386bc',
    storageBucket: 'mysudoku-386bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0BwUg9KVtUaoSvzb7l0ZxJP88oossqfc',
    appId: '1:638773305398:ios:ad0bdbc4662c4f8daaf897',
    messagingSenderId: '638773305398',
    projectId: 'mysudoku-386bc',
    storageBucket: 'mysudoku-386bc.firebasestorage.app',
    iosBundleId: 'com.hoseung.mysudoku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0BwUg9KVtUaoSvzb7l0ZxJP88oossqfc',
    appId: '1:638773305398:ios:ab89958c5e5bdcd5aaf897',
    messagingSenderId: '638773305398',
    projectId: 'mysudoku-386bc',
    storageBucket: 'mysudoku-386bc.firebasestorage.app',
    iosBundleId: 'com.example.mysudoku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjO8eeJWIad5gjVLk9Z-s2lNqQg6lwFBI',
    appId: '1:638773305398:web:12d1a5d08317e364aaf897',
    messagingSenderId: '638773305398',
    projectId: 'mysudoku-386bc',
    authDomain: 'mysudoku-386bc.firebaseapp.com',
    storageBucket: 'mysudoku-386bc.firebasestorage.app',
    measurementId: 'G-F9PNFX7JSZ',
  );
}
